<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2339" started-at="2017-07-28T19:35:39Z" finished-at="2017-07-28T19:35:41Z">
    <groups>
      <group name="myintegration">
        <method signature="Simple2Test.testGetSiteSubscriptions()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testGetSiteSubscriptions" class="recurlytest.Simple2Test"/>
        <method signature="Simple2Test.testUnauthorizedException()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testUnauthorizedException" class="recurlytest.Simple2Test"/>
      </group> <!-- myintegration -->
      <group name="simple">
        <method signature="Simple2Test.testSetAccounts()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testSetAccounts" class="recurlytest.Simple2Test"/>
      </group> <!-- simple -->
    </groups>
    <test name="Default test" duration-ms="2339" started-at="2017-07-28T19:35:39Z" finished-at="2017-07-28T19:35:41Z">
      <class name="recurlytest.Simple2Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="setUp" is-config="true" duration-ms="1171" started-at="2017-07-28T13:35:39Z" finished-at="2017-07-28T13:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="setUp" is-config="true" duration-ms="9" started-at="2017-07-28T13:35:40Z" finished-at="2017-07-28T13:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testGetSiteSubscriptions()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testGetSiteSubscriptions" duration-ms="752" started-at="2017-07-28T13:35:40Z" finished-at="2017-07-28T13:35:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[recurlyClient subscriptions is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: recurlyClient subscriptions is null
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at recurlytest.Simple2Test.testGetSiteSubscriptions(Simple2Test.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSiteSubscriptions -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="tearDown" is-config="true" duration-ms="17" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="setUp" is-config="true" duration-ms="4" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testSetAccounts()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testSetAccounts" duration-ms="214" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.assertNotEquals(Assert.java:897)
	at org.testng.Assert.assertNotEquals(Assert.java:902)
	at recurlytest.Simple2Test.testSetAccounts(Simple2Test.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetAccounts -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="tearDown" is-config="true" duration-ms="4" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="setUp" is-config="true" duration-ms="4" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testUnauthorizedException()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="testUnauthorizedException" duration-ms="121" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[getAccounts call should not succeed with invalid credentials.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: getAccounts call should not succeed with invalid credentials.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at recurlytest.Simple2Test.testUnauthorizedException(Simple2Test.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedException -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="tearDown" is-config="true" duration-ms="2" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:recurlytest.Simple2Test@7c16905e]" name="tearDown" is-config="true" duration-ms="1" started-at="2017-07-28T13:35:41Z" finished-at="2017-07-28T13:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- recurlytest.Simple2Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
